DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TYPE IF EXISTS status_enum CASCADE;
DROP TABLE IF EXISTS requests CASCADE;

CREATE TYPE status_enum AS ENUM ('waiting', 'approved', 'rejected', 'canceled');

CREATE TABLE IF NOT EXISTS users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    users_name  VARCHAR(255) NOT NULL,
    users_email VARCHAR(500) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (users_email)
);

CREATE TABLE IF NOT EXISTS items
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT,
    items_name        VARCHAR(255) NOT NULL,
    items_description VARCHAR(500) NOT NULL,
    items_available   BOOLEAN,
    request_id        BIGINT,
    CONSTRAINT FK_users_id_for_items FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_description VARCHAR(500),
    requestor_id        BIGINT,
    CONSTRAINT FK_requestor_id_for_request FOREIGN KEY (requestor_id) REFERENCES users (id)
);